"""Regenerates src/resources.js from third_party/gem-cutter-iii/.

The page needs the GEM III schema (to build the element tree and show definitions) and the six
report stylesheets. They are kept as plain files under third_party/ and copied, unchanged, into
one script so the page works when opened straight from disk.

    python3 scripts/build_resources.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'third_party', 'gem-cutter-iii')
REPORTS = ['recs', 'detailed', 'rules', 'dvs', 'action', 'gem-cogs']


def js_str(s):
    out = json.dumps(s, ensure_ascii=True)
    return out.replace('</', '<\\/').replace('<!--', '<\\!--')


def read(*parts):
    with open(os.path.join(SRC, *parts), encoding='utf-8') as f:
        return f.read()


lines = [
    '// Generated by scripts/build_resources.py from third_party/gem-cutter-iii/. Do not edit by hand.',
    '// The schema and stylesheets are from GEM Cutter III (Yale Center for Medical Informatics); see',
    '// third_party/gem-cutter-iii/NOTICE.md. They are not covered by this repository\'s license.',
    'const RES = {',
    '  xsd: ' + js_str(read('gemschemaiii.xsd')) + ',',
    '  xsl: {',
]
for key in REPORTS:
    lines.append('    ' + json.dumps(key) + ': ' + js_str(read('xsl', key + '.xsl')) + ',')
lines += ['  },', '};', '']
with open(os.path.join(ROOT, 'src', 'resources.js'), 'w', encoding='ascii') as f:
    f.write('\n'.join(lines))
print('wrote src/resources.js')
