"""Writes the two-page PDF used by the "blood pressure" sample project.

The text is invented for the demonstration. Fonts are embedded (DejaVu Sans, free to embed),
so the page draws the same everywhere. Output: demo/sample_blood_pressure/blood_pressure.pdf
and src/sample_pdf.js (the same bytes as base64, so the page can offer the sample offline).

    python3 scripts/make_sample_pdf.py
"""
import base64, os
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS = '/usr/share/fonts/truetype/dejavu/'
pdfmetrics.registerFont(TTFont('Body', FONTS + 'DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('Bold', FONTS + 'DejaVuSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Ital', FONTS + 'DejaVuSans-Oblique.ttf'))

body = ParagraphStyle('body', fontName='Body', fontSize=10.5, leading=15, spaceAfter=8)
note = ParagraphStyle('note', parent=body, fontName='Ital', fontSize=9.5, textColor='#555555')
h1 = ParagraphStyle('h1', fontName='Bold', fontSize=19, leading=24, spaceAfter=6, textColor='#0d5c52')
h2 = ParagraphStyle('h2', fontName='Bold', fontSize=12.5, leading=17, spaceBefore=12, spaceAfter=5)
NOTE = 'Example guideline. The text is invented to demonstrate GEM Cutter and is not clinical guidance.'

story = [
    Paragraph('Measuring Blood Pressure at Clinic Visits', h1),
    Paragraph(NOTE, note),
    Paragraph('Example Primary Care Network. Released January 2026.', body),
    Paragraph('Purpose', h2),
    Paragraph('This guideline sets out how blood pressure should be measured in adult primary care clinics '
              'so that readings are comparable between visits and between clinicians.', body),
    Paragraph('Intended users', h2),
    Paragraph('Medical assistants, nurses and physicians in primary care clinics.', body),
    Paragraph('Target population', h2),
    Paragraph('Adults aged 18 years or older attending a routine clinic visit. '
              'Pregnant women are outside the scope of this guideline.', body),
    Paragraph('How the guideline was developed', h2),
    Paragraph('A working group of four clinicians searched for studies published from 2010 to 2025 and '
              'graded each recommendation as strong or conditional.', body),
    PageBreak(),
    Paragraph('Recommendations', h2),
    Paragraph('1. Measure blood pressure after the patient has been seated quietly for at least five minutes. '
              '(Strong recommendation; moderate-quality evidence)', body),
    Paragraph('2. Use a validated automated device with a cuff sized to the upper arm of the patient. '
              '(Strong recommendation; high-quality evidence)', body),
    Paragraph('3. If the first reading is 140/90 mm Hg or higher, take two further readings one minute apart '
              'and record the average of the last two. (Conditional recommendation; low-quality evidence)', body),
    Paragraph('Review', h2),
    Paragraph('This guideline will be reviewed every three years, or sooner if new evidence appears.', body),
    Spacer(1, 18),
    Paragraph(NOTE, note),
]

out_dir = os.path.join(ROOT, 'demo', 'sample_blood_pressure')
os.makedirs(out_dir, exist_ok=True)
pdf_path = os.path.join(out_dir, 'blood_pressure.pdf')
doc = SimpleDocTemplate(pdf_path, pagesize=letter, leftMargin=inch, rightMargin=inch, topMargin=inch, bottomMargin=inch,
                        title='Measuring Blood Pressure at Clinic Visits (example)', author='CutGL sample', invariant=1)
doc.build(story)
data = open(pdf_path, 'rb').read()
with open(os.path.join(ROOT, 'src', 'sample_pdf.js'), 'w', encoding='ascii') as f:
    f.write('// Generated by scripts/make_sample_pdf.py: the blood-pressure sample guideline (invented text), as base64.\n')
    f.write('const SAMPLE_PDF_B64 = "' + base64.b64encode(data).decode('ascii') + '";\n')
print('wrote', pdf_path, len(data), 'bytes')
